# -*- coding: utf-8 -*-
"""RL_GNN_OrbitWars.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wfS1KgNsXLTW3v5GsSXw0Lfb8dWTPPAF

# **Install and run Orbit Wars with random agents**
"""

# ── 1. Install ──────────────────────────────────────────────────────────────
!pip install --upgrade "kaggle-environments>=1.28.0"

# ── 2. Imports ──────────────────────────────────────────────────────────────
from kaggle_environments import make
import random
import json

from google.colab import drive
drive.mount('/content/drive')

# ── 3. Create the environment ───────────────────────────────────────────────
env = make("orbit_wars", debug=True)   # Loads the game; debug=True prints errors instead of swallowing them silently

print(f"Environment: {env.name} v{env.version}")
print(f"Players: {env.specification.agents}")
print(f"Max steps: {env.configuration.episodeSteps}")

# ── 4. Define a dead-simple random agent ────────────────────────────────────
def random_agent(obs, config):
    planets = [Planet(*p) for p in obs.planets]

    my_planets = [p for p in planets if p.owner == obs.player]
    if not my_planets:
        return []

    source = random.choice(my_planets)
    target = random.choice(planets)

    # Compute angle from source to target
    angle = math.atan2(target.y - source.y, target.x - source.x)

    # Send a random fraction of ships (between 20% and 80%)
    ships_to_send = int(source.ships * random.uniform(0.2, 0.8))
    if ships_to_send < 1:
        return []

    return [[source.id, angle, ships_to_send]]

# ── 5. Run a short game (2 random agents, 100 steps max) ────────────────────
env.reset()
env.run([random_agent, random_agent])     # Simulates the full game to completion

print("Status :", env.state[0].status)   # DONE / ERROR / ACTIVE
print("Rewards:", env.state[0].reward, env.state[1].reward)

env.render(mode="ipython", width=800, height=600)

"""# **Kaggle Documentation with a greedy agent**

Our first agent uses a simple strategy:

* For each planet we own, find the nearest planet we don't own
* Check if we have enough ships to capture it (need more than the target's garrison)
* Send exactly enough ships to take it (target ships + 1)

### What's wrong with this agent?
The sniper agent has a few problems:

* It doesn't account for travel time - the target planet produces ships while the fleet is in transit
* It sends fleets from every planet, even if multiple are targeting the same planet
* It ignores the sun - fleets aimed through the center get destroyed
* It holds ships on planets that have no nearby targets instead of consolidating



"""

# Run a quick game to see what the observation looks like
env = make("orbit_wars", debug=True)
env.run(["random", "random"])

# Peek at the initial observation
from kaggle_environments.envs.orbit_wars.orbit_wars import Planet, Fleet

obs = env.steps[1][0].observation  # step 1 = first action step
planets = [Planet(*p) for p in obs.planets]
print(f"Player: {obs.player}")
print(f"Angular velocity: {obs.angular_velocity:.4f} rad/turn")
print(f"\nPlanets ({len(planets)}):")
for p in planets[:6]:
    owner_str = f"Player {p.owner}" if p.owner >= 0 else "Neutral"
    print(f"  id={p.id} owner={owner_str:10s} pos=({p.x:.1f}, {p.y:.1f}) r={p.radius:.1f} ships={p.ships} prod={p.production}")

import math
from kaggle_environments.envs.orbit_wars.orbit_wars import Planet

def nearest_planet_sniper(obs):
    moves = []
    player = obs.get("player", 0) if isinstance(obs, dict) else obs.player
    raw_planets = obs.get("planets", []) if isinstance(obs, dict) else obs.planets
    planets = [Planet(*p) for p in raw_planets]

    # Separate our planets from targets
    my_planets = [p for p in planets if p.owner == player]
    targets = [p for p in planets if p.owner != player]

    if not targets:
        return moves

    for mine in my_planets:
        # Find the nearest planet we don't own
        nearest = None
        min_dist = float('inf')
        for t in targets:
            dist = math.sqrt((mine.x - t.x)**2 + (mine.y - t.y)**2)
            if dist < min_dist:
                min_dist = dist
                nearest = t

        if nearest is None:
            continue

        # How many ships do we need? Target's garrison + 1
        ships_needed = max(nearest.ships + 1, 20)

        # Only send if we have enough
        if mine.ships >= ships_needed:
            # Calculate angle from our planet to the target
            angle = math.atan2(nearest.y - mine.y, nearest.x - mine.x)
            moves.append([mine.id, angle, ships_needed])

    return moves

# Test it against the random agent
env = make("orbit_wars", debug=True)
env.run([nearest_planet_sniper, "random"])

final = env.steps[-1]
for i, s in enumerate(final):
    print(f"Player {i}: reward={s.reward}, status={s.status}")

env.render(mode="ipython", width=800, height=600)

"""## **Greedy vs Random Agent**"""

env = make("orbit_wars", debug=True)
env.run([nearest_planet_sniper, random_agent])
env.render(mode="ipython", width=800, height=600)

final = env.steps[-1]
for i, s in enumerate(final):
    print(f"Player {i}: reward={s.reward}, status={s.status}")

"""# **Physics Simulation Toolkit**"""

import math

# ── fleet_speed ──────────────────────────────────────────────────────────────
def fleet_speed(num_ships, max_speed=6.0):
    """
    Returns units/turn for a fleet of num_ships.
    Formula from doc: 1.0 + (maxSpeed - 1.0) * (log(ships) / log(1000)) ^ 1.5
    Edge case: 0 or negative ships returns minimum speed 1.0
    """
    if num_ships <= 1:
        return 1.0
    ratio = math.log(num_ships) / math.log(1000)
    return 1.0 + (max_speed - 1.0) * (ratio ** 1.5)


# ── travel_time ──────────────────────────────────────────────────────────────
def travel_time(x1, y1, x2, y2, num_ships):
    """
    Returns turns (int, rounded up) for a fleet to travel from (x1,y1) to (x2,y2).
    Uses Euclidean distance divided by fleet_speed.
    """
    dist = math.sqrt((x2 - x1)**2 + (y2 - y1)**2)
    speed = fleet_speed(num_ships)
    return math.ceil(dist / speed)

# 1 ship should be slowest, 1000 ships should hit max speed
for n in [1, 10, 50, 100, 500, 1000]:
    print(f"  {n:4d} ships → speed={fleet_speed(n):.3f}")

# A fleet of 50 ships crossing the whole board (~141 units diagonal)
print(f"\n50 ships corner-to-corner: {travel_time(0, 0, 100, 100, 50)} turns")

def hits_sun(x1, y1, x2, y2, sun_x=50, sun_y=50, sun_radius=10):
    """
    Returns True if the line segment from (x1,y1) to (x2,y2)
    passes within sun_radius of the sun center.

    Approach: find the closest point on the segment to the sun,
    then check if that distance < sun_radius.
    """
    # Vector from A to B
    dx, dy = x2 - x1, y2 - y1

    # Vector from A to sun
    fx, fy = sun_x - x1, sun_y - y1

    # t = projection of A->sun onto A->B, clamped to [0,1]
    # t=0 means closest point is A, t=1 means closest point is B
    seg_len_sq = dx*dx + dy*dy
    if seg_len_sq == 0:
        # Source and target are the same point
        dist = math.sqrt(fx*fx + fy*fy)
        return dist < sun_radius

    t = max(0.0, min(1.0, (fx*dx + fy*dy) / seg_len_sq))

    # Closest point on segment to sun
    closest_x = x1 + t * dx
    closest_y = y1 + t * dy

    # Distance from closest point to sun center
    dist = math.sqrt((closest_x - sun_x)**2 + (closest_y - sun_y)**2)

    return dist < sun_radius

# Should be True — straight line through center of board
print(hits_sun(0, 50, 100, 50))   # horizontal through sun

# Should be True — diagonal through center
print(hits_sun(0, 0, 100, 100))

# Should be False — path goes around the top edge
print(hits_sun(0, 0, 100, 0))

# Should be False — path stays in one quadrant
print(hits_sun(60, 60, 90, 90))

def planet_position(planet_id, future_turn, initial_planets, angular_velocity):
    """
    Returns (x, y) of a planet at future_turn.

    Static planets (orbital_radius + planet_radius >= 50) don't move — return initial pos.
    Orbiting planets rotate around sun (50, 50) by angular_velocity each turn.

    planet_id       : int
    future_turn     : int, how many turns from now (0 = current)
    initial_planets : raw list from obs.initial_planets
    angular_velocity: float from obs.angular_velocity
    """
    SUN_X, SUN_Y = 50, 50

    # Find the planet in initial_planets by id
    raw = next(p for p in initial_planets if p[0] == planet_id)
    pid, owner, x0, y0, radius, ships, production = raw

    # Orbital radius = distance from sun at game start
    orbital_radius = math.sqrt((x0 - SUN_X)**2 + (y0 - SUN_Y)**2)

    # Static check: doc says orbiting only if orbital_radius + radius < 50
    if orbital_radius + radius >= 50:
        return (x0, y0)   # doesn't move

    # Initial angle of planet relative to sun
    initial_angle = math.atan2(y0 - SUN_Y, x0 - SUN_X)

    # Angle at future_turn
    angle_at_t = initial_angle + angular_velocity * future_turn

    # New position
    x = SUN_X + orbital_radius * math.cos(angle_at_t)
    y = SUN_Y + orbital_radius * math.sin(angle_at_t)

    return (x, y)

env = make("orbit_wars", debug=True)
env.reset()
obs = env.state[0].observation

# Find an orbiting planet
from kaggle_environments.envs.orbit_wars.orbit_wars import Planet
initial = obs.initial_planets
ang_vel = obs.angular_velocity

# Print positions of planet 0 at turns 0, 10, 50, and one full revolution
full_rev = int((2 * math.pi) / ang_vel)
print(f"Angular velocity : {ang_vel:.4f} rad/turn")
print(f"Full revolution  : {full_rev} turns\n")

for t in [0, 10, 50, full_rev]:
    pos = planet_position(0, t, initial, ang_vel)
    print(f"  turn {t:4d} → ({pos[0]:.2f}, {pos[1]:.2f})")

env.render(mode="ipython", width=800, height=600)

# Find which planets are orbiting vs static
SUN_X, SUN_Y = 50, 50

for raw in initial:
    pid, owner, x0, y0, radius, ships, production = raw
    orbital_radius = math.sqrt((x0 - SUN_X)**2 + (y0 - SUN_Y)**2)
    is_orbiting = (orbital_radius + radius) < 50
    if is_orbiting:
        print(f"  planet {pid:2d} → orbital_radius={orbital_radius:.2f}, radius={radius:.2f}, ORBITING ✅")

env = make("orbit_wars", debug=True)
env.reset()
obs = env.state[0].observation

# Find an orbiting planet
from kaggle_environments.envs.orbit_wars.orbit_wars import Planet
initial = obs.initial_planets
ang_vel = obs.angular_velocity

# Print positions of planet 0 at turns 0, 10, 50, and one full revolution
full_rev = int((2 * math.pi) / ang_vel)
print(f"Angular velocity : {ang_vel:.4f} rad/turn")
print(f"Full revolution  : {full_rev} turns\n")

for t in [0, 10, 50, full_rev]:
    pos = planet_position(12, t, initial, ang_vel)
    print(f"  turn {t:4d} → ({pos[0]:.2f}, {pos[1]:.2f})")

env.render(mode="ipython", width=800, height=600)

def comet_position(comet_group, comet_idx, future_turn):
    """
    Returns (x, y) of a specific comet at future_turn, or None if off the board.

    comet_group : one entry from obs.comets
    comet_idx   : which comet in the group (0-3, matches planet_ids order)
    future_turn : turns from NOW (0 = current position)
    """
    path = comet_group["paths"][comet_idx]
    current_index = comet_group["path_index"]

    target_index = current_index + future_turn

    if target_index >= len(path):
        return None   # comet has left the board

    x, y = path[target_index]
    return (x, y)

env = make("orbit_wars", debug=True)
env.run(["random", "random"])

# Find a step where comets exist (they spawn at step 50)
for step_idx, step in enumerate(env.steps):
    obs = step[0].observation
    if obs.comets:
        print(f"Step {step_idx}")
        cg = obs.comets[0]   # first comet group
        print(f"  keys        : {list(cg.keys())}")
        print(f"  planet_ids  : {cg['planet_ids']}")
        print(f"  path_index  : {cg['path_index']}")
        print(f"  paths type  : {type(cg['paths'])}")
        print(f"  paths length: {len(cg['paths'])}")
        print(f"  paths[0]    : {cg['paths'][0]}")   # first entry — is it [x,y] or another list?
        break

for step_idx, step in enumerate(env.steps):
    obs = step[0].observation
    if obs.comets:
        cg = obs.comets[0]
        path_len = len(cg["paths"][0])
        print(f"Total path length: {path_len} steps\n")

        for t in [0, 5, 10, path_len - 1, path_len]:
            pos = comet_position(cg, 0, t)   # comet 0 in group
            print(f"  future_turn={t:3d} → {pos}")
        break

def intercept_point(source_x, source_y, target_planet_id, num_ships,
                    current_turn, initial_planets, angular_velocity):
    """
    Returns (x, y, eta) — where to aim and how long the fleet will take.

    Iterative approach:
      1. Guess ETA using current planet position
      2. Predict where planet will be at current_turn + ETA
      3. Recompute ETA using that new position
      4. Repeat until ETA stops changing (converges in ~3-5 iterations)
    """
    # Start with current planet position as first guess
    x, y = planet_position(target_planet_id, current_turn,
                            initial_planets, angular_velocity)

    eta = travel_time(source_x, source_y, x, y, num_ships)

    for _ in range(10):   # 10 iterations is more than enough
        # Predict planet position at arrival
        x, y = planet_position(target_planet_id, current_turn + eta,
                                initial_planets, angular_velocity)

        new_eta = travel_time(source_x, source_y, x, y, num_ships)

        if new_eta == eta:
            break   # converged

        eta = new_eta

    return (x, y, eta)

env = make("orbit_wars", debug=True)
env.reset()
obs = env.state[0].observation
initial = obs.initial_planets
ang_vel = obs.angular_velocity
current_turn = 0

# Current position of planet 12
current_pos = planet_position(12, 0, initial, ang_vel)
print(f"Planet 12 current pos : ({current_pos[0]:.2f}, {current_pos[1]:.2f})")

# Intercept from corner (0, 0) with 50 ships
ix, iy, eta = intercept_point(0, 0, 12, 50, current_turn, initial, ang_vel)
print(f"Intercept point       : ({ix:.2f}, {iy:.2f})")
print(f"ETA                   : {eta} turns")

# Verify — planet position at arrival should match intercept point
verify = planet_position(12, eta, initial, ang_vel)
print(f"Planet pos at ETA     : ({verify[0]:.2f}, {verify[1]:.2f})")

# Commented out IPython magic to ensure Python compatibility.
# %%writefile physics.py
# 
# import math
# 
# # ── fleet_speed ──────────────────────────────────────────────────────────────
# def fleet_speed(num_ships, max_speed=6.0):
#     """
#     Returns units/turn for a fleet of num_ships.
#     Formula from doc: 1.0 + (maxSpeed - 1.0) * (log(ships) / log(1000)) ^ 1.5
#     Edge case: 0 or negative ships returns minimum speed 1.0
#     """
#     if num_ships <= 1:
#         return 1.0
#     ratio = math.log(num_ships) / math.log(1000)
#     return 1.0 + (max_speed - 1.0) * (ratio ** 1.5)
# 
# 
# # ── travel_time ──────────────────────────────────────────────────────────────
# def travel_time(x1, y1, x2, y2, num_ships):
#     """
#     Returns turns (int, rounded up) for a fleet to travel from (x1,y1) to (x2,y2).
#     Uses Euclidean distance divided by fleet_speed.
#     """
#     dist = math.sqrt((x2 - x1)**2 + (y2 - y1)**2)
#     speed = fleet_speed(num_ships)
#     return math.ceil(dist / speed)
# 
# def hits_sun(x1, y1, x2, y2, sun_x=50, sun_y=50, sun_radius=10):
#     """
#     Returns True if the line segment from (x1,y1) to (x2,y2)
#     passes within sun_radius of the sun center.
# 
#     Approach: find the closest point on the segment to the sun,
#     then check if that distance < sun_radius.
#     """
#     # Vector from A to B
#     dx, dy = x2 - x1, y2 - y1
# 
#     # Vector from A to sun
#     fx, fy = sun_x - x1, sun_y - y1
# 
#     # t = projection of A->sun onto A->B, clamped to [0,1]
#     # t=0 means closest point is A, t=1 means closest point is B
#     seg_len_sq = dx*dx + dy*dy
#     if seg_len_sq == 0:
#         # Source and target are the same point
#         dist = math.sqrt(fx*fx + fy*fy)
#         return dist < sun_radius
# 
#     t = max(0.0, min(1.0, (fx*dx + fy*dy) / seg_len_sq))
# 
#     # Closest point on segment to sun
#     closest_x = x1 + t * dx
#     closest_y = y1 + t * dy
# 
#     # Distance from closest point to sun center
#     dist = math.sqrt((closest_x - sun_x)**2 + (closest_y - sun_y)**2)
# 
#     return dist < sun_radius
# 
# def planet_position(planet_id, future_turn, initial_planets, angular_velocity):
#     """
#     Returns (x, y) of a planet at future_turn.
# 
#     Static planets (orbital_radius + planet_radius >= 50) don't move — return initial pos.
#     Orbiting planets rotate around sun (50, 50) by angular_velocity each turn.
# 
#     planet_id       : int
#     future_turn     : int, how many turns from now (0 = current)
#     initial_planets : raw list from obs.initial_planets
#     angular_velocity: float from obs.angular_velocity
#     """
#     SUN_X, SUN_Y = 50, 50
# 
#     # Find the planet in initial_planets by id
#     raw = next(p for p in initial_planets if p[0] == planet_id)
#     pid, owner, x0, y0, radius, ships, production = raw
# 
#     # Orbital radius = distance from sun at game start
#     orbital_radius = math.sqrt((x0 - SUN_X)**2 + (y0 - SUN_Y)**2)
# 
#     # Static check: doc says orbiting only if orbital_radius + radius < 50
#     if orbital_radius + radius >= 50:
#         return (x0, y0)   # doesn't move
# 
#     # Initial angle of planet relative to sun
#     initial_angle = math.atan2(y0 - SUN_Y, x0 - SUN_X)
# 
#     # Angle at future_turn
#     angle_at_t = initial_angle + angular_velocity * future_turn
# 
#     # New position
#     x = SUN_X + orbital_radius * math.cos(angle_at_t)
#     y = SUN_Y + orbital_radius * math.sin(angle_at_t)
# 
#     return (x, y)
# 
# def comet_position(comet_group, comet_idx, future_turn):
#     """
#     Returns (x, y) of a specific comet at future_turn, or None if off the board.
# 
#     comet_group : one entry from obs.comets
#     comet_idx   : which comet in the group (0-3, matches planet_ids order)
#     future_turn : turns from NOW (0 = current position)
#     """
#     path = comet_group["paths"][comet_idx]
#     current_index = comet_group["path_index"]
# 
#     target_index = current_index + future_turn
# 
#     if target_index >= len(path):
#         return None   # comet has left the board
# 
#     x, y = path[target_index]
#     return (x, y)
# 
# def intercept_point(source_x, source_y, target_planet_id, num_ships,
#                     current_turn, initial_planets, angular_velocity):
#     """
#     Returns (x, y, eta) — where to aim and how long the fleet will take.
# 
#     Iterative approach:
#       1. Guess ETA using current planet position
#       2. Predict where planet will be at current_turn + ETA
#       3. Recompute ETA using that new position
#       4. Repeat until ETA stops changing (converges in ~3-5 iterations)
#     """
#     # Start with current planet position as first guess
#     x, y = planet_position(target_planet_id, current_turn,
#                             initial_planets, angular_velocity)
# 
#     eta = travel_time(source_x, source_y, x, y, num_ships)
# 
#     for _ in range(10):   # 10 iterations is more than enough
#         # Predict planet position at arrival
#         x, y = planet_position(target_planet_id, current_turn + eta,
#                                 initial_planets, angular_velocity)
# 
#         new_eta = travel_time(source_x, source_y, x, y, num_ships)
# 
#         if new_eta == eta:
#             break   # converged
# 
#         eta = new_eta
# 
#     return (x, y, eta)

"""# **Building a Physics Informed Heuristic Agent**"""

import math

def score_target(source_planet, target_planet, my_player_id,
                 current_turn, initial_planets, angular_velocity,
                 ships_to_send = None):
    """
    Returns a float score for sending a fleet from source to target.
    Higher score = more desirable action.

    source_planet, target_planet: Planet named tuples
    my_player_id: int so we know (enemy or neutral)
    ships_to_send: if None, half of source's ships are sent
    """

    if ships_to_send is None:
        ships_to_send = max(1, source_planet.ships // 2)

    # ------------------ ETA to intercept ponts -----------
    ix, iy, eta = intercept_point(source_planet.x, source_planet.y,
                                  target_planet.id, ships_to_send,
                                  current_turn, initial_planets,
                                  angular_velocity)

    # penalize long travel times
    time_score = 1.0 / eta

    # -------- Affordability of target (> 1, can take it) ---
    # neutral, enemy -> need target.ships + 1
    # ours -> not allowed

    ships_needed = target_planet.ships + 1
    affordability = ships_to_send / max(ships_needed, 1)

    # ------- Production value -------------
    prod_score = target_planet.production / 5.0

    # ---------- combine -----------------------
    score = (time_score) * min(affordability, 2.0)

    return score

    # ---------- Design Notes -----------------
    # production scoring hurts early game — pure time + affordability is better

def assign_targets(my_planets, enemy_and_neutral_planets, my_player_id,
                   current_turn, initial_planets, angular_velocity,
                   ship_fraction=0.9):
    """
    Assigns each of our planets a target to send ships to.

    Returns a dict: {source_planet.id: (target_planet, ships_to_send)}

    my_planets        : list of Planets we own
    enemy_and_neutral_planets: list of Planets we don't own
    ship_fraction     : fraction of ships to send (default 80%); keep some for defence

    """

    assignments = {} # source_id -> (target_planet, ships_to_send)

    # Track how many times each target has been assiged so we don't ignore pile-on
    target_assignment_count = {}

    # Build a flat list of all (score, source, target, ships)
    candidates = []

    for src in my_planets:
        ships_to_send = max(1, int(src.ships * ship_fraction))

        for tgt in enemy_and_neutral_planets:
          s = score_target(src, tgt, my_player_id,
                           current_turn, initial_planets, angular_velocity,
                           ships_to_send)
          candidates.append((s, src, tgt, ships_to_send))

      # best opportunities first
    candidates.sort(key=lambda c: c[0], reverse=True)
    assigned_sources = set()

    for score, src, tgt, ships_to_send in candidates:
      # skip if already assigned
        if src.id in assigned_sources:
          continue

        if target_assignment_count.get(tgt.id,0)>=2:
          continue

        assignments[src.id] = (tgt, ships_to_send)
        assigned_sources.add(src.id)
        target_assignment_count[tgt.id] = target_assignment_count.get(tgt.id, 0) + 1

    return assignments

def safe_angle(src_x, src_y, target_x, target_y,
               sun_x=50, sun_y=50, sun_radius=10,
               nudge_deg = 5, max_attempts = 36):
  """
  Returns a safe angle (in radians) from source to the target, while avoiding the sun

  If the direct path is clear, returns the direct angle unchanged. Otherwise,
  tries nudging left and right in increments of nudge_de until a clear path is found

  None -> no safe angle found
  """


  direct_angle = math.atan2(target_y - src_y, target_x - src_x)

  # Fast path
  if not hits_sun(src_x, src_y, target_x, target_y, sun_x, sun_y, sun_radius):
      return direct_angle
  nudge_rad = math.radians(nudge_deg)

  for i in range(1, max_attempts +1):
      for sign in (+1, -1):
          angle = direct_angle + sign * i * nudge_rad

          dist = 200
          end_x = src_x + dist * math.cos(angle)
          end_y = src_y + dist * math.sin(angle)

          if not hits_sun(src_x, src_y, end_x, end_y, sun_x, sun_y, sun_radius):
              return angle
  return None

#------------ Design notes -----------------
# alternate sweeping +1, -1 to avoid bias
# we give up after 180 deg in each direction (36 max attempts)
# need to recompute travel_time later

from collections import namedtuple

Planet = namedtuple('Planet', ['id', 'owner', 'x', 'y', 'radius', 'ships', 'production'])

def heuristic_agent(obs, config):
    """
    Main agent function compatible with kaggle-environments.

    obs    : observation object from the environment
    config : config object (we use config.episodeSteps if needed)

    Returns a list of actions: [[source_id, angle_radians, ships_to_send], ...]
    """

    my_player_id = obs.player
    current_turn = getattr(obs, 'step', 0)
    initial_planets = obs.initial_planets
    angular_velocity = obs.angular_velocity

    # --- Step 1: Parse planets ---
    planets = [
        Planet(
            id=p[0],
            owner=p[1],
            x=p[2],
            y=p[3],
            radius=p[4],
            ships=p[5],
            production=p[6]
        )
        for p in obs.planets
    ]

    # --- Step 2: Split by ownership ---
    my_planets = [p for p in planets if p.owner == my_player_id]
    other_planets = [p for p in planets if p.owner != my_player_id]

    # Nothing to do if we have no planets
    if not my_planets or not other_planets:
        return []

    # --- Step 3: Get assignments ---
    assignments = assign_targets(
        my_planets, other_planets, my_player_id,
        current_turn, initial_planets, angular_velocity
    )

    # --- Step 4: Build action list ---
    actions = []

    for src in my_planets:
        if src.id not in assignments:
            continue  # idle planet — no assignment found

        tgt, ships_to_send = assignments[src.id]

        # Compute intercept point (aim at where planet WILL be, not where it is)
        ix, iy, eta = intercept_point(
            src.x, src.y,
            tgt.id,
            ships_to_send,
            current_turn,
            initial_planets,
            angular_velocity
        )

        # Get a sun-safe angle toward the intercept point
        angle = safe_angle(src.x, src.y, ix, iy)

        if angle is None:
            # No safe path exists — skip this action rather than fly into the sun
            continue

        # Guard: never send 0 ships
        if ships_to_send <= 0:
            continue

        actions.append([src.id, angle, ships_to_send])

    return actions

from kaggle_environments import make

def evaluate(agent_a, agent_b, n_games=20, debug=False):
    """
    Runs n_games between agent_a and agent_b, alternating who goes first
    to avoid first-player advantage skewing results.

    Returns a dict with win/loss/draw counts and win rate for agent_a.
    """
    global _game_env
    results = {"win": 0, "loss": 0, "draw": 0}

    for i in range(n_games):
        env = make("orbit_wars", debug=debug)

        # Alternate who plays as player 0 each game
        if i % 2 == 0:
            agents = [agent_a, agent_b]
        else:
            agents = [agent_b, agent_a]

        env.run(agents)

        # Rewards: 1.0 = win, 0.0 = loss, 0.5 = draw
        rewards = [s.reward for s in env.state]

        a_reward = rewards[0] if i % 2 == 0 else rewards[1]

        if a_reward == 1:
            results["win"] += 1
        elif a_reward == -1:
            results["loss"] += 1
        else:
            results["draw"] += 1

    results["win_rate"] = results["win"] / n_games
    print(f"Results over {n_games} games:")
    print(f"  Wins:   {results['win']}")
    print(f"  Losses: {results['loss']}")
    print(f"  Draws:  {results['draw']}")
    print(f"  Win rate: {results['win_rate']:.1%}")

    return results

env = make("orbit_wars", debug=True)
env.run([nearest_planet_sniper, heuristic_agent])

final = env.steps[-1]
for i, s in enumerate(final):
    print(f"Player {i}: reward={s.reward}, status={s.status}")

env.render(mode="ipython", width=800, height=600)

env = make("orbit_wars", debug=True)
env.run([heuristic_agent, nearest_planet_sniper])

# check how many turns had non-empty actions
# kaggle logs all steps
total_steps = len(env.steps)
print(f"Total steps: {total_steps}")

# count turns where our agent did something
active_turns = sum(1 for step in env.steps if step[0].action not in (None, []))
print(f"Turns we acted: {active_turns}")

results = evaluate(heuristic_agent, nearest_planet_sniper, n_games=200)

env = make("orbit_wars", debug=True)
env.run([random_agent, heuristic_agent])

final = env.steps[-1]
for i, s in enumerate(final):
    print(f"Player {i}: reward={s.reward}, status={s.status}")

env.render(mode="ipython", width=800, height=600)

results = evaluate(heuristic_agent, random_agent, n_games=200)

"""# **Key Strategy: Beam Search**

**Initial Strategy: Monte Carlo Tree Search** (MCTS) *Lite*

*Explanation for dummies (me)*:

A regular heuristic agent asks: *"what's the best action right now?"*
MCTS asks: **"if I play this action, and then both sides play reasonably for the rest of the game, who wins?"**

It does this by building a tree of possible futures, one node per game state. The four steps that repeat every iteration:

1. **Selection** — starting from the root (current game state), walk down the tree picking the most promising node at each level. "Most promising" balances exploitation (nodes that have won before) vs exploration (nodes we haven't tried much). This is the UCB1 formula:

<center>
$UCB1 = \frac{w}{n}+C\sqrt{\frac{ln N}{n}}, $
</center>
where: $\frac{w}{n}$: win rate of the node (exploitation), $N$: visits to the parent, $n$: visits to this node (exploration), $C$: exploration constant (typically $\sqrt{2}$).

2. **Expansion** - at a leaf node (one we haven't explored yet), add its children (one per candidate action).

3. **Simulation** - from the new node, play the game to completion using our heuristic agent for both sides. Record who wins.

4. **Backpropagation** - walk back up the tree, updating each node's win count and visit count.

> Refer arXiv:2103.04931v4 [cs.AI] for more details

> Why this doesn't work? Long simulation times.

**Actual Strategy: Beam Search**
At each decision point, instead of exploring one action (greedy) or all actions (full tree), you keep the top K candidates — called the "beam width". You expand only those K, evaluate their children, keep the top K again, and repeat for a fixed depth.

At each level you prune ruthlessly — only the top K survive regardless of which parent they came from.

MCTS needs many iterations to build up reliable visit counts before UCB1 means anything. With only 4-10 iterations you're essentially random.
Beam search makes no such assumption — it does one pass, evaluates every node once, and picks the best. With a fixed K and depth D you know exactly how many deepcopy calls you'll make: K × D. Predictable, budgetable.

> Beam search can miss the best action if it gets pruned early — it's not guaranteed optimal like full tree search. But in practice for fast games with tight time budgets it tends to outperform broken MCTS significantly.
"""

#-------------- Helper function --------------------------------
def to_obs(raw_obs):
    """
    Converts a Struct or dict observation into a SimpleNamespace
    so we can always use dot notation safely.
    """
    from types import SimpleNamespace
    if isinstance(raw_obs, dict):
        ns = SimpleNamespace(**raw_obs)
        if not hasattr(ns, 'step'):
            ns.step = raw_obs.get('step', 0)
        return ns
    return raw_obs

#-------------- Helper function --------------------------------
def _get_candidate_actions(obs):
    """
    Generates diverse candidate actions by varying the TARGET planet.
    For each owned planet, considers its top-3 targets by score_target().
    """
    candidates = []
    seen = set()

    planets = [Planet(p[0],p[1],p[2],p[3],p[4],p[5],p[6]) for p in obs.planets]
    my_planets = [p for p in planets if p.owner == obs.player]
    other_planets = [p for p in planets if p.owner != obs.player]

    if not my_planets or not other_planets:
        return candidates

    TOP_TARGETS = 3
    SHIP_FRACTION = 0.7

    for src in my_planets:
        ships_to_send = max(1, int(src.ships * SHIP_FRACTION))

        scored = []
        for tgt in other_planets:
            s = score_target(src, tgt, obs.player, obs.step, obs.initial_planets, obs.angular_velocity)
            scored.append((s, tgt))

        scored.sort(reverse=True)
        top_targets = [tgt for _, tgt in scored[:TOP_TARGETS]]

        for tgt in top_targets:
            ix, iy, eta = intercept_point(
                src.x, src.y, tgt.id, ships_to_send,
                obs.step, obs.initial_planets, obs.angular_velocity
            )
            angle = safe_angle(src.x, src.y, ix, iy)
            if angle is None or ships_to_send <= 0:
                continue

            action = [[src.id, angle, ships_to_send]]
            key = (src.id, round(angle, 3))
            if key not in seen:
                seen.add(key)
                candidates.append(action)

    return candidates

#-------------- Helper function --------------------------------
def sync_env_to_obs(game_env, real_obs):
    """
    Overwrites the internal env's observation with the real game state.
    This ensures MCTS searches from the true current state, not a stale one.

    real_obs : the obs passed into mcts_agent each turn (true game state)
    game_env : our global environment to sync
    """
    for i in range(len(game_env.state)):
        internal_obs = game_env.state[i].observation

        # overwrite all state fields
        internal_obs.planets = real_obs.planets
        internal_obs.fleets = real_obs.fleets
        internal_obs.step = real_obs.step
        internal_obs.angular_velocity = real_obs.angular_velocity
        internal_obs.initial_planets = real_obs.initial_planets
        internal_obs.next_fleet_id = real_obs.next_fleet_id
        internal_obs.comets = real_obs.comets
        internal_obs.comet_planet_ids = real_obs.comet_planet_ids
        # note: we don't overwrite player — each state keeps its own player id

# ------------- Helper Function ---------------------
def evaluate_position(obs, my_player_id):
    """
    Heuristic evaluation of a game state for my_player_id.
    Returns a float in [0, 1] — higher is better for my_player_id.

    Uses ship count only (planets + in-transit fleets).
    No production weighting — consistent with score_target findings.
    """
    planets = [Planet(*p) for p in obs.planets]

    my_ships = sum(p.ships for p in planets if p.owner == my_player_id)
    enemy_ships = sum(p.ships for p in planets if p.owner != my_player_id and p.owner != -1)

    if hasattr(obs, 'fleets') and obs.fleets:
        for f in obs.fleets:
            if f[1] == my_player_id:
                my_ships += f[5]
            elif f[1] != -1:
                enemy_ships += f[5]

    total = my_ships + enemy_ships
    if total == 0:
        return 0.5

    return my_ships / total

import time
import copy
def beam_search_agent(obs, config):
    """
    Beam search agent with depth=1, beam_width=3.

    Candidates are pre-ranked by score_target and capped at K=3
    before any simulation — keeps time per turn bounded regardless
    of how many planets we own.
    """
    global _mcts_env

    K = 3
    my_player_id = obs.player
    opp_player_id = 1 - my_player_id
    start_time = time.time()

    # sync global env to true game state
    sync_env_to_obs(_mcts_env, obs)

    # generate and pre-rank candidates by score_target — no deepcopy yet
    candidate_actions = _get_candidate_actions(obs)
    if not candidate_actions:
        return heuristic_agent(obs, config)

    # pre-score each candidate cheaply using score_target
    planets = [Planet(*p) for p in obs.planets]
    my_planets = {p.id: p for p in planets if p.owner == my_player_id}
    other_planets = {p.id: p for p in planets if p.owner != my_player_id}

    prescored = []
    for action in candidate_actions:
        src_id = action[0][0]
        src = my_planets.get(src_id)
        if src is None:
            continue
        # score against best available target
        best = max(
            score_target(src, tgt, my_player_id, obs.step,
                        obs.initial_planets, obs.angular_velocity)
            for tgt in other_planets.values()
        )
        prescored.append((best, action))

    prescored.sort(reverse=True)
    top_candidates = [action for _, action in prescored[:K]]

    # simulate only top K candidates
    scored = []
    for action in top_candidates:
        sim_env = copy.deepcopy(_mcts_env)
        opp_obs = to_obs(sim_env.state[opp_player_id].observation)
        opp_action = heuristic_agent(opp_obs, None)

        if my_player_id == 0:
            sim_env.step([action, opp_action])
        else:
            sim_env.step([opp_action, action])

        result_obs = to_obs(sim_env.state[my_player_id].observation)
        score = evaluate_position(result_obs, my_player_id)
        scored.append((score, action))

    scored.sort(reverse=True)
    best_score, best_action = scored[0]

    #print(f"Turn {obs.step} — beam: {len(candidate_actions)} → {len(top_candidates)} candidates, "
          #f"best score: {best_score:.3f}, time: {time.time()-start_time:.3f}s")
    #print(f"best_action: {best_action}")
    #return best_action

    return best_action

_mcts_env = make("orbit_wars", debug=False)
_mcts_env.reset()

env = make("orbit_wars", debug=True)
env.run([beam_search_agent, heuristic_agent])

final = env.steps[-1]
for i, s in enumerate(final):
    print(f"Player {i}: reward={s.reward}, status={s.status}")

env.render(mode="ipython", width=800, height=600)

evaluate(beam_search_agent, heuristic_agent, n_games = 25)

evaluate(beam_search_agent, heuristic_agent, n_games = 200)

env = make("orbit_wars", debug=True)
env.run([beam_search_agent, nearest_planet_sniper])

final = env.steps[-1]
for i, s in enumerate(final):
    print(f"Player {i}: reward={s.reward}, status={s.status}")

env.render(mode="ipython", width=800, height=600)

evaluate(beam_search_agent, nearest_planet_sniper, n_games = 25)

evaluate(beam_search_agent, nearest_planet_sniper, n_games = 200)

"""# **Imitation Learning**"""

import numpy as np

MAX_SHIPS = 500.0   # normalization constant
MAX_STEP  = 400.0   # typical game length
MAP_SIZE  = 100.0   # x, y lie in roughly [0, 100]

def obs_to_features(obs, my_player_id):
    """
    Convert a raw observation into a flat numpy feature vector.

    Planet features (per planet, sorted by planet id):
        x, y               — raw coordinates (the GNN will use relative positions later;
                             for the MLP we keep absolute for simplicity)
        owner_encoded      — 0: neutral, 1: me, 2: opponent
        ships_norm         — ships / MAX_SHIPS
        production_norm    — production / max_production (computed from initial_planets)

    Global features (appended at the end):
        step_norm          — obs.step / MAX_STEP
        my_ships_norm      — total my ships / MAX_SHIPS
        opp_ships_norm     — total opponent ships / MAX_SHIPS
    """
    planets = [Planet(*p) for p in obs.planets]
    planets.sort(key=lambda p: p.id)   # consistent ordering

    max_production = max(p.production for p in planets) or 1.0

    planet_features = []
    my_total_ships  = 0.0
    opp_total_ships = 0.0

    for p in planets:
        # encode owner relative to current player
        if p.owner == -1:
            owner_enc = 0        # neutral
        elif p.owner == my_player_id:
            owner_enc = 1        # mine
        else:
            owner_enc = 2        # opponent

        planet_features.extend([
            p.x/ MAP_SIZE,
            p.y/ MAP_SIZE,
            owner_enc,
            p.ships / MAX_SHIPS,
            p.production / max_production,
        ])

        if p.owner == my_player_id:
            my_total_ships += p.ships
        elif p.owner != -1:
            opp_total_ships += p.ships

    global_features = [
        obs.step / MAX_STEP,
        my_total_ships  / MAX_SHIPS,
        opp_total_ships / MAX_SHIPS,
    ]

    return np.array(planet_features + global_features, dtype=np.float32)

import os
os.makedirs("/content/drive/MyDrive/OrbitWars", exist_ok=True)

import pickle

def collect_imitation_data(n_games=200, verbose=True):
    """
    Run n_games of BeamSearch vs BeamSearch and record
    (feature_vector, source_id, angle, ship_count_norm) at every turn.

    Returns a list of dicts, one per turn per game.
    """
    global _mcts_env

    dataset = []

    for game_idx in range(n_games):
        # fresh environment for each game
        env = make("orbit_wars", debug=False)
        env.reset()

        # point the global env used inside beam_search_agent to this game's env
        _mcts_env = env

        done = False
        while not done:
            # collect action and features for player 0
            obs0  = to_obs(env.state[0].observation)
            act0  = beam_search_agent(obs0, None)

            # collect action and features for player 1
            _mcts_env = env
            obs1  = to_obs(env.state[1].observation)
            act1  = beam_search_agent(obs1, None)

            # skip turns where a player has no valid moves (e.g. lost all planets)
            if not act0 or not act1:
                env.step([act0, act1])
                done = (env.state[0].status != "ACTIVE")
                continue

            # now safe to unpack
            feat0 = obs_to_features(obs0, my_player_id=0)
            src0, angle0, ships0 = act0[0]

            feat1 = obs_to_features(obs1, my_player_id=1)
            src1, angle1, ships1 = act1[0]

            # log both players' turns as separate training samples
            dataset.append({
                "features":       feat0,
                "source_id":      int(src0),
                "angle":          float(angle0),
                "ship_count_norm": float(ships0) / MAX_SHIPS,
            })
            dataset.append({
                "features":       feat1,
                "source_id":      int(src1),
                "angle":          float(angle1),
                "ship_count_norm": float(ships1) / MAX_SHIPS,
            })

            # step the environment
            state = env.step([act0, act1])
            done  = (env.state[0].status != "ACTIVE")

        if verbose and (game_idx + 1) % 10 == 0:
            print(f"Collected {game_idx + 1}/{n_games} games — {len(dataset)} samples so far")

    return dataset


def save_dataset(dataset, path="/content/drive/MyDrive/OrbitWars/imitation_data.pkl"):
    with open(path, "wb") as f:
        pickle.dump(dataset, f)
    print(f"Saved {len(dataset)} samples to {path}")

dataset = collect_imitation_data(n_games=1)
save_dataset(dataset)

